config {
  type:"table",
  database:"ibadatatrust",
  schema:"silver",
  name:"Ref_customer",
  description:"This table contains unique customer records from the bronze customer table, with data quality transformations applied."
}




with customer_id_counts as (
  select
    customer_id,
    count(*) as id_count
  from ${ref("customer")}
  group by customer_id
)
--  demo
select
  c.customer_id,
  IFNULL(NULLIF(c.first_name, ''), 'N/A') as first_name,-- Demo
  IFNULL(NULLIF(c.last_name, ''), 'N/A') as last_name,
  c.phone_number,
  c.address,
  c.city,
  c.state,
  c.zip_code,
  c.country,
  c.date_of_birth,
  c.age,
  c.account_status,
  c.last_activity_date,
  c.registration_date
from ${ref("customer")} c
join customer_id_counts cic on c.customer_id = cic.customer_id
where cic.id_count = 1